parameters:
#    razer_back_end.example.class: Razer\BackEndBundle\Example

services:
#    razer_back_end.example:
#        class: %razer_back_end.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
